{
  "openapi": "3.1.0",
  "info": {
    "version": "2.0.0",
    "title": "Lichess.org API reference",
    "contact": {
      "name": "Lichess.org API",
      "url": "https://lichess.org/api",
      "email": "contact@lichess.org"
    },
    "x-logo": {
      "url": "https://lichess1.org/assets/logo/lichess-pad12.svg"
    },
    "license": {
      "name": "AGPL-3.0-or-later",
      "url": "https://www.gnu.org/licenses/agpl-3.0.txt"
    },
    "description": "# Introduction\nWelcome to the reference for the Lichess API! Lichess is free/libre,\nopen-source chess server powered by volunteers and donations.\n- Get help in the [Lichess Discord channel](https://discord.gg/lichess)\n- API demo app with OAuth2 login and gameplay: [source](https://github.com/lichess-org/api-demo) / [demo](https://lichess-org.github.io/api-demo/)\n- API UI app with OAuth2 login and endpoint forms: [source](https://github.com/lichess-org/api-ui) / [website][...]"
  },
  "servers": [
    {
      "url": "https://lichess.org"
    }
  ],
  "tags": [
    {
      "name": "Account",
      "description": "Read and write account information and preferences.\n<https://lichess.org/account/preferences/game-display>\n"
    },
    {
      "name": "Users",
      "description": "Access registered users on Lichess.\n<https://lichess.org/player>\n\n- Each user blog exposes an atom (RSS) feed, like <https://lichess.org/@/thibault/blog.atom>\n- User blogs mashup feed: https://lichess.org/blog/community.atom\n- User blogs mashup feed for a language: https://lichess.org/blog/community/fr.atom\n"
    },
    {
      "name": "Relations",
      "description": "Access relations between users.\n"
    },
    {
      "name": "Games",
      "description": "Access games played on Lichess.\n<https://lichess.org/games>\n"
    },
    {
      "name": "TV",
      "description": "Access Lichess TV channels and games.\n<https://lichess.org/tv> & <https://lichess.org/games>\n"
    },
    {
      "name": "Puzzles",
      "description": "Access Lichess [puzzle history and dashboard](https://lichess.org/training).\n\nOur collection of puzzles is in the public domain, you can [download it here](https://database.lichess.org/#puzzles).\nFor a list of our puzzle themes with their description, check out the [theme translation file](https://github.com/ornicar/lila/blob/master/translation/source/puzzleTheme.xml).\nThe daily puzzle can be [posted in your slack workspace](https://lichess.org/daily-puzzle-slack).\n"
    },
    {
      "name": "Teams",
      "description": "Access and manage Lichess teams and their members.\n<https://lichess.org/team>\n"
    },
    {
      "name": "Board",
      "description": "Play on Lichess with physical boards and third-party clients.\nWorks with normal Lichess accounts. Engine play or assistance is [forbidden](https://lichess.org/page/fair-play).\n\n### Features\n- [Stream incoming chess moves](#operation/boardGameStream)\n- [Play chess moves](#operation/boardGameMove)\n- [Read](#operation/boardGameStream) and [write](#operation/boardGameChatPost) in the player and spectator chats\n- [Receive](#operation/apiStreamEvent), [create](#operation/c[...]"
    },
    {
      "name": "Bot",
      "description": "Play on Lichess as a bot. Allows engine play.\nRead the [blog post announcement of lichess bots](https://lichess.org/blog/WvDNticAAMu_mHKP/welcome-lichess-bots).\n\nOnly works with [Bot accounts](#operation/botAccountUpgrade).\n\n### Features\n- [Stream incoming chess moves](#operation/botGameStream)\n- [Play chess moves](#operation/botGameMove)\n- [Read](#operation/botGameStream) and [write](#operation/botGameChat) in the player and spectator chats\n- [Receive](#operation/[...]"
    },
    {
      "name": "Challenges",
      "description": "Send and receive challenges to play.\n\nTo create a lot of challenges, consider [bulk pairing](#operation/bulkPairingCreate) instead.\n"
    },
    {
      "name": "Bulk pairings",
      "description": "Create many games for other players.\n\nThese endpoints are intended for tournament organisers.\n"
    },
    {
      "name": "Arena tournaments",
      "description": "Access Arena tournaments played on Lichess.\n[Official Arena tournaments](https://lichess.org/tournament) are maintained by Lichess,\nbut you can [create your own Arena tournaments](https://lichess.org/tournament/new) as well.\n"
    },
    {
      "name": "Swiss tournaments",
      "description": "Access Swiss tournaments played on Lichess.\n[Read more about Swiss tournaments.](https://lichess.org/swiss).\n"
    },
    {
      "name": "Simuls",
      "description": "Access simuls played on Lichess.\n<https://lichess.org/simul>\n"
    },
    {
      "name": "Studies",
      "description": "Access Lichess studies.\n<https://lichess.org/study>\n"
    },
    {
      "name": "Messaging",
      "description": "Private messages with other players.\n<https://lichess.org/inbox>\n"
    },
    {
      "name": "Broadcasts",
      "description": "Relay chess events on Lichess.\n[Official broadcasts](https://lichess.org/broadcast) are maintained by Lichess,\nbut you can [create your own broadcasts](https://lichess.org/broadcast/new) to cover any live game or chess event.\nYou will need to publish PGN on a public URL so that Lichess can pull updates from it.\nAlternatively, you can push PGN updates to Lichess using [this API endpoint](#tag/Broadcasts/operation/broadcastPush).\n\nBroadcasts are organized in tournaments[...]"
    },
    {
      "name": "FIDE",
      "description": "FIDE players and federations from [their public download](https://ratings.fide.com/download_lists.phtml).\n\n<https://lichess.org/fide>\n"
    },
    {
      "name": "Analysis",
      "description": "Access Lichess cloud evaluations database.\n<https://lichess.org/analysis>\n"
    },
    {
      "name": "External engine",
      "description": "**This API is in alpha and subject to change.**\n\nUse or provide external engine analysis.\n\nExternal engines can provide analysis on pages like the\n[analysis board](https://lichess.org/analysis), running as a service\noutside of the browser, or even on a different machine.\n"
    },
    {
      "name": "Opening Explorer",
      "description": "Lookup positions from the [Lichess opening explorer](https://lichess.org/analysis#explorer).\n\nRuns <https://github.com/lichess-org/lila-openingexplorer>.\n\n**The endpoint hostname is not lichess.org but explorer.lichess.ovh.**\n"
    },
    {
      "name": "Tablebase",
      "description": "Lookup positions from the [Lichess tablebase server](https://lichess.org/blog/W3WeMyQAACQAdfAL/7-piece-syzygy-tablebases-are-complete).\n\n**The endpoint hostname is not lichess.org but tablebase.lichess.ovh.**\n"
    },
    {
      "name": "OAuth",
      "description": "Obtaining and revoking OAuth tokens.\n\n[Read about the Lichess API authentication methods and code examples](https://github.com/lichess-org/api/blob/master/example/README.md).\n"
    }
  ],
  "paths": {
    "/api/users/status": {
      "get": {
        "operationId": "apiUsersStatus",
        "summary": "Get real-time users status",
        "description": "Read the `online`, `playing` and `streaming` flags of several users.\nThis API is very fast and cheap on lichess side.\nSo you can call it quite often (like once every 5 seconds).\nUse it to track players and know when they're connected on lichess and playing games.\n",
        "tags": [
          "Users"
        ],
        "security": []
      }
    },
    "/api/player": {
      "get": {
        "operationId": "player",
        "summary": "Get all top 10",
        "tags": [
          "Users"
        ],
        "security": [],
        "description": "Get the top 10 players for each speed and variant.\nSee <https://lichess.org/player>.\n"
      }
    },
    "/api/player/top/{nb}/{perfType}": {
      "get": {
        "operationId": "playerTopNbPerfType",
        "summary": "Get one leaderboard",
        "tags": [
          "Users"
        ],
        "security": [],
        "description": "Get the leaderboard for a single speed or variant (a.k.a. `perfType`).\nThere is no leaderboard for correspondence or puzzles.\nSee <https://lichess.org/player/top/200/bullet>.\n"
      }
    },
    "/api/user/{username}": {
      "get": {
        "operationId": "apiUser",
        "summary": "Get user public data",
        "description": "Read public data of a user.\n",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/user/{username}/rating-history": {
      "get": {
        "operationId": "apiUserRatingHistory",
        "summary": "Get rating history of a user",
        "description": "Read rating history of a user, for all perf types.\nThere is at most one entry per day.\nFormat of an entry is `[year, month, day, rating]`.\n`month` starts at zero (January).\n",
        "tags": [
          "Users"
        ],
        "security": []
      }
    },
    "/api/user/{username}/perf/{perf}": {
      "get": {
        "operationId": "apiUserPerf",
        "summary": "Get performance statistics of a user",
        "description": "Read performance statistics of a user, for a single performance.\nSimilar to the [performance pages on the website](https://lichess.org/@/thibault/perf/bullet).\n",
        "tags": [
          "Users"
        ],
        "security": []
      }
    },
    "/api/user/{username}/activity": {
      "get": {
        "operationId": "apiUserActivity",
        "summary": "Get user activity",
        "description": "Read data to generate the activity feed of a user.\n",
        "tags": [
          "Users"
        ],
        "security": []
      }
    },
    "/api/puzzle/daily": {
      "get": {
        "operationId": "apiPuzzleDaily",
        "summary": "Get the daily puzzle",
        "description": "Get the daily Lichess puzzle in JSON format.\nAlternatively, you can [post it in your slack workspace](https://lichess.org/daily-puzzle-slack).\n",
        "tags": [
          "Puzzles"
        ],
        "security": []
      }
    },
    "/api/puzzle/{id}": {
      "get": {
        "operationId": "apiPuzzleId",
        "summary": "Get a puzzle by its ID",
        "description": "Get a single Lichess puzzle in JSON format.",
        "tags": [
          "Puzzles"
        ],
        "security": []
      }
    },
    "/api/puzzle/next": {
      "get": {
        "operationId": "apiPuzzleNext",
        "summary": "Get a new puzzle",
        "description": "Get a random Lichess puzzle in JSON format.\n\nIf authenticated, only returns puzzles that the user has never seen before.\n\n**DO NOT** use this endpoint to enumerate puzzles for mass download. Instead, download the [full public puzzle database](https://database.lichess.org/#puzzles).\n",
        "tags": [
          "Puzzles"
        ],
        "security": [
          {
            "OAuth2": [
              "puzzle:read"
            ]
          }
        ]
      }
    },
    "/api/puzzle/activity": {
      "get": {
        "operationId": "apiPuzzleActivity",
        "summary": "Get your puzzle activity",
        "description": "Download your puzzle activity in [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.\nPuzzle activity is sorted by reverse chronological order (most recent first)\nWe recommend streaming the response, for it can be very long.\n",
        "tags": [
          "Puzzles"
        ],
        "security": [
          {
            "OAuth2": [
              "puzzle:read"
            ]
          }
        ]
      }
    },
    "/api/puzzle/replay/{days}/{theme}": {
      "get": {
        "operationId": "apiPuzzleReplay",
        "summary": "Get puzzles to replay",
        "description": "Gets the puzzle IDs of remaining puzzles to re-attempt in JSON format.",
        "tags": [
          "Puzzles"
        ],
        "security": [
          {
            "OAuth2": [
              "puzzle:read"
            ]
          }
        ]
      }
    },
    "/api/puzzle/dashboard/{days}": {
      "get": {
        "operationId": "apiPuzzleDashboard",
        "summary": "Get your puzzle dashboard",
        "description": "Download your [puzzle dashboard](https://lichess.org/training/dashboard/30/dashboard) as JSON.\nAlso includes all puzzle themes played, with aggregated results.\nAllows re-creating the [improvement/strengths](https://lichess.org/training/dashboard/30/improvementAreas) interfaces.\n",
        "tags": [
          "Puzzles"
        ],
        "security": [
          {
            "OAuth2": [
              "puzzle:read"
            ]
          }
        ]
      }
    },
    "/api/storm/dashboard/{username}": {
      "get": {
        "operationId": "apiStormDashboard",
        "summary": "Get the storm dashboard of a player",
        "description": "Download the [storm dashboard](https://lichess.org/storm/dashboard/mrbasso) of any player as JSON.\nContains the aggregated highscores, and the history of storm runs aggregated by days.\nUse `?days=0` if you only care about the highscores.\n",
        "tags": [
          "Puzzles"
        ],
        "security": []
      }
    },
    "/api/racer": {
      "post": {
        "operationId": "racerPost",
        "summary": "Create and join a puzzle race",
        "description": "Create a new private [puzzle race](https://lichess.org/racer).\nThe Lichess user who creates the race must join the race page,\nand manually start the race when enough players have joined.\n- <https://lichess.org/racer>\n",
        "tags": [
          "Puzzles"
        ],
        "security": [
          {
            "OAuth2": [
              "racer:write"
            ]
          }
        ]
      }
    },
    "/api/users": {
      "post": {
        "operationId": "apiUsers",
        "summary": "Get users by ID",
        "tags": [
          "Users"
        ],
        "security": [],
        "description": "Get up to 300 users by their IDs. Users are returned in the same order as the IDs.\nThe method is `POST` to allow a longer list of IDs to be sent in the request body.\nPlease do not try to download all the Lichess users with this endpoint, or any other endpoint.\nAn API is not a way to fully export a website. We do not provide a full download of the Lichess users.\nThis endpoint is limited to 8,000 users every 10 minutes, and 120,000 every day.\n"
      }
    },
    "/api/account": {
      "get": {
        "operationId": "accountMe",
        "summary": "Get my profile",
        "description": "Public information about the logged in user.\n",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/account/email": {
      "get": {
        "operationId": "accountEmail",
        "summary": "Get my email address",
        "description": "Read the email address of the logged in user.\n",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "OAuth2": [
              "email:read"
            ]
          }
        ]
      }
    },
    "/api/account/preferences": {
      "get": {
        "operationId": "account",
        "summary": "Get my preferences",
        "description": "Read the preferences of the logged in user.\n- <https://lichess.org/account/preferences/game-display>\n- <https://github.com/ornicar/lila/blob/master/modules/pref/src/main/Pref.scala>\n",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "OAuth2": [
              "preference:read"
            ]
          }
        ]
      }
    },
    "/api/account/kid": {
      "get": {
        "operationId": "accountKid",
        "summary": "Get my kid mode status",
        "description": "Read the kid mode status of the logged in user.\n- <https://lichess.org/account/kid>\n",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "OAuth2": [
              "preference:read"
            ]
          }
        ]
      },
      "post": {
        "operationId": "accountKidPost",
        "summary": "Set my kid mode status",
        "description": "Set the kid mode status of the logged in user.\n- <https://lichess.org/account/kid>\n",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "OAuth2": [
              "preference:write"
            ]
          }
        ]
      }
    },
    "/api/timeline": {
      "get": {
        "operationId": "timeline",
        "summary": "Get my timeline",
        "description": "Get the timeline events of the logged in user.\n",
        "tags": [
          "Account"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/game/export/{gameId}": {
      "get": {
        "operationId": "gamePgn",
        "summary": "Export one game",
        "description": "Download one game in either PGN or JSON format.\nOngoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.\n",
        "tags": [
          "Games"
        ],
        "security": []
      }
    },
    "/api/user/{username}/current-game": {
      "get": {
        "operationId": "apiUserCurrentGame",
        "summary": "Export ongoing game of a user",
        "description": "Download the ongoing game, or the last game played, of a user.\nAvailable in either PGN or JSON format.\nOngoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.\n",
        "tags": [
          "Games"
        ],
        "security": []
      }
    },
    "/api/games/user/{username}": {
      "get": {
        "operationId": "apiGamesUser",
        "summary": "Export games of a user",
        "description": "Download all games of any user in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.\nGames are sorted by reverse chronological order (most recent first).\nWe recommend streaming the response, for it can be very long.\n<https://lichess.org/@/german11> for instance has more than 500,000 games.\nThe game stream is throttled, depending on who is making the request:\n  - Anonymous request: 20 games per second\n  - [OAuth2 authenticated](#section/Introductio[...]",
        "tags": [
          "Games"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/games/export/_ids": {
      "post": {
        "operationId": "gamesExportIds",
        "summary": "Export games by IDs",
        "description": "Download games by IDs in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request `Accept` header.\nGames are sorted by reverse chronological order (most recent first)\nThe method is `POST` so a longer list of IDs can be sent in the request body.\n300 IDs can be submitted.\nOngoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.\n",
        "tags": [
          "Games"
        ],
        "security": []
      }
    },
    "/api/stream/games-by-users": {
      "post": {
        "operationId": "gamesByUsers",
        "summary": "Stream games of users",
        "description": "Stream the games played between a list of users, in real time.\nOnly games where **both players** are part of the list are included.\nThe stream emits an event each time a game is started or finished.\nTo also get all current ongoing games at the beginning of the stream, use the `withCurrentGames` flag.\nGames are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nMaximum number of users: 300.\nThe method is `POST` so a longer list of IDs can be sent in [...]",
        "tags": [
          "Games"
        ],
        "security": []
      }
    },
    "/api/stream/games/{streamId}": {
      "post": {
        "operationId": "gamesByIds",
        "summary": "Stream games by IDs",
        "description": "Creates a stream of games from an arbitrary streamId, and a list of game IDs.\nThe stream first outputs the games that already exists, then emits an event each time a game is started or finished.\nGames are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nMaximum number of games: 500 for anonymous requests, or 1000 for [OAuth2 authenticated](#section/Introduction/Authentication) requests.\nWhile the stream is open, it is possible to [add new game IDs t[...]",
        "tags": [
          "Games"
        ],
        "security": []
      }
    },
    "/api/stream/games/{streamId}/add": {
      "post": {
        "operationId": "gamesByIdsAdd",
        "summary": "Add game IDs to stream",
        "description": "Add new game IDs for [an existing stream](#operation/gamesByIds) to watch.\nThe stream will immediately outputs the games that already exists, then emit an event each time a game is started or finished.\n",
        "tags": [
          "Games"
        ],
        "security": []
      }
    },
    "/api/account/playing": {
      "get": {
        "operationId": "apiAccountPlaying",
        "summary": "Get my ongoing games",
        "description": "Get the ongoing games of the current user.\nReal-time and correspondence games are included.\nThe most urgent games are listed first.\n",
        "tags": [
          "Games"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/stream/game/{id}": {
      "get": {
        "operationId": "streamGame",
        "summary": "Stream moves of a game",
        "description": "Stream positions and moves of any ongoing game, in [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nA description of the game is sent as a first message.\nThen a message is sent each time a move is played.\nFinally a description of the game is sent when it finishes, and the stream is closed.\nOngoing games are delayed by a few seconds ranging from 3 to 60 depending on the time control, as to prevent cheat bots from using this API.\nNo more than 8 game streams can [...]",
        "tags": [
          "Games"
        ],
        "security": []
      }
    },
    "/api/import": {
      "post": {
        "operationId": "gameImport",
        "summary": "Import one game",
        "description": "Import a game from PGN. See <https://lichess.org/paste>.\nRate limiting: 200 games per hour for OAuth requests, 100 games per hour for anonymous requests.\nTo broadcast ongoing games, consider [pushing to a broadcast instead](#operation/broadcastPush).\nTo analyse a position or a line, just construct an analysis board URL:\n[https://lichess.org/analysis/pgn/e4_e5_Nf3_Nc6_Bc4_Bc5_Bxf7+](https://lichess.org/analysis/pgn/e4_e5_Nf3_Nc6_Bc4_Bc5_Bxf7+)\n",
        "tags": [
          "Games"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/games/export/imports": {
      "get": {
        "operationId": "apiImportedGamesUser",
        "summary": "Export your imported games",
        "description": "Download all games imported by you. Games are exported in PGN format.",
        "tags": [
          "Games"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/games/export/bookmarks": {
      "get": {
        "operationId": "apiExportBookmarks",
        "summary": "Export your bookmarked games",
        "description": "Download all games bookmarked by you, in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.\nGames are sorted by reverse chronological order (most recent first).\nWe recommend streaming the response, for it can be very long.\n",
        "tags": [
          "Games"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/tv/channels": {
      "get": {
        "operationId": "tvChannels",
        "summary": "Get current TV games",
        "description": "Get basic info about the best games being played for each speed and variant,\nbut also computer games and bot games.\nSee [lichess.org/tv](https://lichess.org/tv).\n",
        "tags": [
          "TV"
        ],
        "security": []
      }
    },
    "/api/tv/feed": {
      "get": {
        "operationId": "tvFeed",
        "summary": "Stream current TV game",
        "description": "Stream positions and moves of the current [TV game](https://lichess.org/tv) in [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nTry it with `curl https://lichess.org/api/tv/feed`.\n",
        "tags": [
          "TV"
        ],
        "security": []
      }
    },
    "/api/tv/{channel}/feed": {
      "get": {
        "operationId": "tvChannelFeed",
        "summary": "Stream current TV game of a TV channel",
        "description": "Stream positions and moves of a current [TV channel's game](https://lichess.org/tv/rapid) in [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nTry it with `curl https://lichess.org/api/tv/rapid/feed`.\n",
        "tags": [
          "TV"
        ],
        "security": []
      }
    },
    "/api/tv/{channel}": {
      "get": {
        "operationId": "tvChannelGames",
        "summary": "Get best ongoing games of a TV channel",
        "description": "Get a list of ongoing games for a given TV channel. Similar to [lichess.org/games](https://lichess.org/games).\nAvailable in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request `Accept` header.\n",
        "tags": [
          "TV"
        ],
        "security": []
      }
    },
    "/api/tournament": {
      "get": {
        "operationId": "apiTournament",
        "summary": "Get current tournaments",
        "description": "Get recently active and finished tournaments.\nThis API is used to display the [Lichess tournament schedule](https://lichess.org/tournament).\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": []
      },
      "post": {
        "operationId": "apiTournamentPost",
        "summary": "Create a new Arena tournament",
        "description": "Create a public or private Arena tournament.\nThis endpoint mirrors the form on <https://lichess.org/tournament/new>.\nYou can create up to 12 public tournaments per day, or 24 private tournaments.\nA team battle can be created by specifying the `teamBattleByTeam` argument.\nAdditional restrictions:\n  - clockTime + clockIncrement > 0\n  - 15s and 0+1 variant tournaments cannot be rated\n  - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes *[...]",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/tournament/{id}": {
      "get": {
        "operationId": "tournament",
        "summary": "Get info about an Arena tournament",
        "description": "Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": []
      },
      "post": {
        "operationId": "apiTournamentUpdate",
        "summary": "Update an Arena tournament",
        "description": "Update an Arena tournament.\nBe mindful not to make important changes to ongoing tournaments.\nCan be used to update a team battle.\nAdditional restrictions:\n  - clockTime + clockIncrement > 0\n  - 15s and 0+1 variant tournaments cannot be rated\n  - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes * 60) / (96 * clockTime + 48 * clockIncrement + 15) <= 150\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/tournament/{id}/join": {
      "post": {
        "operationId": "apiTournamentJoin",
        "summary": "Join an Arena tournament",
        "description": "Join an Arena tournament, possibly with a password and/or a team.\nAlso unpauses if you had previously [paused](#operation/apiTournamentWithdraw) the tournament.\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/tournament/{id}/withdraw": {
      "post": {
        "operationId": "apiTournamentWithdraw",
        "summary": "Pause or leave an Arena tournament",
        "description": "Leave a future Arena tournament, or take a break on an ongoing Arena tournament.\nIt's possible to join again later. Points and streaks are preserved.\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/tournament/{id}/terminate": {
      "post": {
        "operationId": "apiTournamentTerminate",
        "summary": "Terminate an Arena tournament",
        "description": "Terminate an Arena tournament\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/tournament/team-battle/{id}": {
      "post": {
        "operationId": "apiTournamentTeamBattlePost",
        "summary": "Update a team battle",
        "description": "Set the teams and number of leaders of a team battle.\nTo update the other attributes of a team battle, use the [tournament update endpoint](#operation/apiTournamentUpdate).\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/tournament/{id}/games": {
      "get": {
        "operationId": "gamesByTournament",
        "summary": "Export games of an Arena tournament",
        "description": "Download games of a tournament in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.\nGames are sorted by reverse chronological order (most recent first).\nThe game stream is throttled, depending on who is making the request:\n  - Anonymous request: 20 games per second\n  - [OAuth2 authenticated](#section/Introduction/Authentication) request: 30 games per second\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": []
      }
    },
    "/api/tournament/{id}/results": {
      "get": {
        "operationId": "resultsByTournament",
        "summary": "Get results of an Arena tournament",
        "description": "Players of an Arena tournament, with their score and performance, sorted by rank (best first).\n**Players are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON)**, i.e. one JSON object per line.\nIf called on an ongoing tournament, results can be inconsistent\ndue to ranking changes while the players are being streamed.\nUse on finished tournaments for guaranteed consistency.\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": []
      }
    },
    "/api/tournament/{id}/teams": {
      "get": {
        "operationId": "teamsByTournament",
        "summary": "Get team standing of a team battle",
        "description": "Teams of a team battle tournament, with top players, sorted by rank (best first).\n",
        "tags": [
          "Arena tournaments"
        ],
        "security": []
      }
    },
    "/api/user/{username}/tournament/created": {
      "get": {
        "operationId": "apiUserNameTournamentCreated",
        "summary": "Get tournaments created by a user",
        "description": "Get all tournaments created by a given user.\nTournaments are sorted by reverse chronological order of start date (last starting first).\nTournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nThe stream is throttled, depending on who is making the request:\n  - Anonymous request: 20 tournaments per second\n  - [OAuth2 authenticated](#section/Introduction/Authentication) request: 30 tournaments per second\n  - Authenticated, downloading your [...]",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/user/{username}/tournament/played": {
      "get": {
        "operationId": "apiUserNameTournamentPlayed",
        "summary": "Get tournaments played by a user",
        "description": "Get all tournaments played by a given user.\nTournaments are sorted by reverse chronological order of start date (last played first).\nTournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nThe stream is throttled, depending on who is making the request:\n  - Anonymous request: 20 tournaments per second\n  - [OAuth2 authenticated](#section/Introduction/Authentication) request: 30 tournaments per second\n  - Authenticated, downloading your own[...]",
        "tags": [
          "Arena tournaments"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/swiss/new/{teamId}": {
      "post": {
        "operationId": "apiSwissNew",
        "summary": "Create a new Swiss tournament",
        "description": "Create a Swiss tournament for your team.\nThis endpoint mirrors the Swiss tournament form from your team pagee.\nYou can create up to 12 tournaments per day.\nAdditional restrictions:\n  - clock.limit + clock.increment > 0\n  - 15s and 0+1 variant tournaments cannot be rated\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/swiss/{id}": {
      "get": {
        "operationId": "swiss",
        "summary": "Get info about a Swiss tournament",
        "description": "Get detailed info about a Swiss tournament.\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": []
      }
    },
    "/api/swiss/{id}/edit": {
      "post": {
        "operationId": "apiSwissUpdate",
        "summary": "Update a Swiss tournament",
        "description": "Update a Swiss tournament.\nBe mindful not to make important changes to ongoing tournaments.\nAdditional restrictions:\n  - clock.limit + clock.increment > 0\n  - 15s and 0+1 variant tournaments cannot be rated\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/swiss/{id}/schedule-next-round": {
      "post": {
        "operationId": "apiSwissScheduleNextRound",
        "summary": "Manually schedule the next round",
        "description": "Manually schedule the next round date and time of a Swiss tournament.\nThis sets the `roundInterval` field to `99999999`, i.e. manual scheduling.\nAll further rounds will need to be manually scheduled, unless the `roundInterval` field is changed back to automatic scheduling.\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/swiss/{id}/join": {
      "post": {
        "operationId": "apiSwissJoin",
        "summary": "Join a Swiss tournament",
        "description": "Join a Swiss tournament, possibly with a password.\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/swiss/{id}/withdraw": {
      "post": {
        "operationId": "apiSwissWithdraw",
        "summary": "Pause or leave a swiss tournament",
        "description": "Leave a future Swiss tournament, or take a break on an ongoing Swiss tournament.\nIt's possible to join again later. Points are preserved.\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/api/swiss/{id}/terminate": {
      "post": {
        "operationId": "apiSwissTerminate",
        "summary": "Terminate a Swiss tournament",
        "description": "Terminate a Swiss tournament\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": [
          {
            "OAuth2": [
              "tournament:write"
            ]
          }
        ]
      }
    },
    "/swiss/{id}.trf": {
      "get": {
        "operationId": "swissTrf",
        "summary": "Export TRF of a Swiss tournament",
        "description": "Download a tournament in the Tournament Report File format, the FIDE standard.\nDocumentation: <https://www.fide.com/FIDE/handbook/C04Annex2_TRF16.pdf>\nExample: <https://lichess.org/swiss/j8rtJ5GL.trf>\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": []
      }
    },
    "/api/swiss/{id}/games": {
      "get": {
        "operationId": "gamesBySwiss",
        "summary": "Export games of a Swiss tournament",
        "description": "Download games of a swiss tournament in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.\nGames are sorted by chronological order.\nThe game stream is throttled, depending on who is making the request:\n  - Anonymous request: 20 games per second\n  - [OAuth2 authenticated](#section/Introduction/Authentication) request: 30 games per second\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": []
      }
    },
    "/api/swiss/{id}/results": {
      "get": {
        "operationId": "resultsBySwiss",
        "summary": "Get results of a swiss tournament",
        "description": "Players of a swiss tournament, with their score and performance, sorted by rank (best first).\nPlayers are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nIf called on an ongoing tournament, results can be inconsistent\ndue to ranking changes while the players are being streamed.\nUse on finished tournaments for guaranteed consistency.\n",
        "tags": [
          "Swiss tournaments"
        ],
        "security": []
      }
    },
    "/api/team/{teamId}/swiss": {
      "get": {
        "operationId": "apiTeamSwiss",
        "summary": "Get team swiss tournaments",
        "description": "Get all swiss tournaments of a team.\nTournaments are sorted by reverse chronological order of start date (last starting first).\nTournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n",
        "tags": [
          "Teams",
          "Swiss tournaments"
        ],
        "security": []
      }
    },
    "/api/study/{studyId}/{chapterId}.pgn": {
      "get": {
        "operationId": "studyChapterPgn",
        "summary": "Export one study chapter",
        "description": "Download one study chapter in PGN format.\n",
        "tags": [
          "Studies"
        ],
        "security": []
      }
    },
    "/api/study/{studyId}.pgn": {
      "get": {
        "operationId": "studyAllChaptersPgn",
        "summary": "Export all chapters",
        "description": "Download all chapters of a study in PGN format.\n",
        "tags": [
          "Studies"
        ],
        "security": []
      },
      "head": {
        "operationId": "studyAllChaptersHead",
        "summary": "Study metadata",
        "description": "Only get the study headers, including `Last-Modified`.\n",
        "tags": [
          "Studies"
        ],
        "security": []
      }
    },
    "/api/study/{studyId}/import-pgn": {
      "post": {
        "operationId": "apiStudyImportPGN",
        "summary": "Import PGN into a study",
        "description": "Imports arbitrary PGN into an existing [study](https://lichess.org/study). Creates a new chapter in the study.\nIf the PGN contains multiple games (separated by 2 or more newlines)\nthen multiple chapters will be created within the study.\nNote that a study can contain at most 64 chapters.\n",
        "tags": [
          "Studies"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ]
      }
    },
    "/study/by/{username}/export.pgn": {
      "get": {
        "operationId": "studyExportAllPgn",
        "summary": "Export all studies of a user",
        "description": "Download all chapters of all studies of a user in PGN format.\nIf authenticated, then all public, unlisted, and private studies are included.\nIf not, only public (non-unlisted) studies are included.\n",
        "tags": [
          "Studies"
        ],
        "security": [
          {
            "OAuth2": [
              "study:read"
            ]
          }
        ]
      }
    },
    "/api/study/by/{username}": {
      "get": {
        "operationId": "studyListMetadata",
        "summary": "List studies of a user",
        "description": "Get metadata (name and dates) of all studies of a user.\nIf authenticated, then all public, unlisted, and private studies are included.\nIf not, only public (non-unlisted) studies are included.\nStudies are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n",
        "tags": [
          "Studies"
        ],
        "security": [
          {
            "OAuth2": [
              "study:read"
            ]
          }
        ]
      }
    },
    "/api/study/{studyId}/{chapterId}": {
      "delete": {
        "operationId": "apiStudyStudyIdChapterIdDelete",
        "summary": "Delete a study chapter",
        "tags": [
          "Studies"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ],
        "description": "Delete a chapter of a study you own. This is definitive.\nA study must have at least one chapter; so if you delete the last chapter,\nan empty one will be automatically created to replace it.\n"
      }
    },
    "/api/broadcast": {
      "get": {
        "operationId": "broadcastsOfficial",
        "summary": "Get official broadcasts",
        "description": "Get all incoming, ongoing, and finished official broadcasts.\nThe broadcasts are sorted by start date, most recent first.\nBroadcasts are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/api/broadcast/top": {
      "get": {
        "operationId": "broadcastsTop",
        "summary": "Get paginated top broadcast previews",
        "description": "The same data, in the same order, as can be seen on [https://lichess.org/broadcast](/broadcast).\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/api/broadcast/by/{username}": {
      "get": {
        "operationId": "broadcastsByUser",
        "summary": "Get broadcasts created by a user",
        "description": "Get all incoming, ongoing, and finished official broadcasts.\nThe broadcasts are sorted by created date, most recent first.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/broadcast/new": {
      "post": {
        "operationId": "broadcastTourCreate",
        "summary": "Create a broadcast tournament",
        "description": "Create a new broadcast tournament to relay external games.\nThis endpoint accepts the same form data as the [web form](https://lichess.org/broadcast/new).\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ]
      }
    },
    "/api/broadcast/{broadcastTournamentId}": {
      "get": {
        "operationId": "broadcastTourGet",
        "summary": "Get a broadcast tournament",
        "description": "Get information about a broadcast tournament.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/broadcast/{broadcastTournamentId}/players": {
      "get": {
        "operationId": "broadcastPlayersGet",
        "summary": "Get players of a broadcast",
        "description": "Get the list of players of a broadcast tournament, if available.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/broadcast/{broadcastTournamentId}/edit": {
      "post": {
        "operationId": "broadcastTourUpdate",
        "summary": "Update your broadcast tournament",
        "description": "Update information about a broadcast tournament that you created.\nThis endpoint accepts the same form data as the web form.\nAll fields must be populated with data. Missing fields will override the broadcast with empty data.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ]
      }
    },
    "/broadcast/{broadcastTournamentId}/new": {
      "post": {
        "operationId": "broadcastRoundCreate",
        "summary": "Create a broadcast round",
        "description": "Create a new broadcast round to relay external games.\nThis endpoint accepts the same form data as the web form.\n\nChoose one between `syncUrl`, `syncUrls`, `syncIds` and `syncUsers`, if it is missing, the broadcast needs to be fed by [pushing PGN to it](#operation/broadcastPush)\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ]
      }
    },
    "/api/broadcast/{broadcastTournamentSlug}/{broadcastRoundSlug}/{broadcastRoundId}": {
      "get": {
        "operationId": "broadcastRoundGet",
        "summary": "Get a broadcast round",
        "description": "Get information about a broadcast round.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/broadcast/round/{broadcastRoundId}/edit": {
      "post": {
        "operationId": "broadcastRoundUpdate",
        "summary": "Update a broadcast round",
        "description": "Update information about a broadcast round.\nThis endpoint accepts the same form data as the web form.\nAll fields must be populated with data. Missing fields will override the broadcast with empty data.\nFor instance, if you omit `startDate`, then any pre-existing start date will be removed.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ]
      }
    },
    "/api/broadcast/round/{broadcastRoundId}/reset": {
      "post": {
        "operationId": "broadcastRoundReset",
        "summary": "Reset a broadcast round",
        "description": "Remove any games from the broadcast round and reset it to its initial state.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ]
      }
    },
    "/api/broadcast/round/{broadcastRoundId}/push": {
      "post": {
        "operationId": "broadcastPush",
        "summary": "Push PGN to a broadcast round",
        "description": "Update a broadcast with new PGN.\nOnly for broadcasts without a source URL.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:write"
            ]
          }
        ]
      }
    },
    "/api/stream/broadcast/round/{broadcastRoundId}.pgn": {
      "get": {
        "operationId": "broadcastStreamRoundPgn",
        "summary": "Stream an ongoing broadcast tournament as PGN",
        "description": "This streaming endpoint first sends all games of a broadcast tournament in PGN format.\nThen, it waits for new moves to be played. As soon as it happens, the entire PGN of the game is sent to the stream.\nThe stream will also send PGNs when games are added to the tournament.\nThis is the best way to get updates about an ongoing tournament. Streaming means no polling,\nand no pollings means no latency, and minimum impact on the server.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/api/broadcast/round/{broadcastRoundId}.pgn": {
      "get": {
        "operationId": "broadcastRoundPgn",
        "summary": "Export one round as PGN",
        "description": "Download all games of a single round of a broadcast tournament in PGN format.\nYou *could* poll this endpoint to get updates about a tournament, but it would be slow,\nand very inefficient.\nInstead, consider [streaming the tournament](#operation/broadcastStreamRoundPgn) to get\na new PGN every time a game is updated, in real-time.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": []
      }
    },
    "/api/broadcast/{broadcastTournamentId}.pgn": {
      "get": {
        "operationId": "broadcastAllRoundsPgn",
        "summary": "Export all rounds as PGN",
        "description": "Download all games of all rounds of a broadcast in PGN format.\nIf a `study:read` [OAuth token](#tag/OAuth) is provided,\nthe private rounds where the user is a contributor will be available.\nYou may want to [download only the games of a single round](#operation/broadcastRoundPgn) instead.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:read"
            ]
          }
        ]
      }
    },
    "/api/broadcast/my-rounds": {
      "get": {
        "operationId": "broadcastMyRoundsGet",
        "summary": "Get your broadcast rounds",
        "description": "Stream all broadcast rounds you are a member of.\nAlso includes broadcasts rounds you did not create, but were invited to.\nAlso includes broadcasts rounds where you're a non-writing member. See the `writeable` flag in the response.\nRounds are ordered by rank, which is roughly chronological, most recent first, slightly pondered with popularity.\n",
        "tags": [
          "Broadcasts"
        ],
        "security": [
          {
            "OAuth2": [
              "study:read"
            ]
          }
        ]
      }
    },
    "/api/fide/player/{playerId}": {
      "get": {
        "operationId": "fidePlayerGet",
        "summary": "Get a FIDE player",
        "description": "Get information about a FIDE player.\n",
        "tags": [
          "FIDE"
        ],
        "security": []
      }
    },
    "/api/fide/player": {
      "get": {
        "operationId": "fidePlayerSearch",
        "summary": "Search FIDE players",
        "description": "List of FIDE players search results for a query.\n",
        "tags": [
          "FIDE"
        ],
        "security": []
      }
    },
    "/api/simul": {
      "get": {
        "operationId": "apiSimul",
        "summary": "Get current simuls",
        "description": "Get recently created, started, finished, simuls.\nCreated and finished simul lists are not exhaustives, only those with\nstrong enough host will be listed, the same filter is used to display simuls on https://lichess.org/simul.\nWhen [authenticated with OAuth2](#section/Introduction/Authentication), the pending list will be populated with your created, but unstarted simuls.\n",
        "tags": [
          "Simuls"
        ],
        "security": []
      }
    },
    "/api/team/{teamId}": {
      "get": {
        "operationId": "teamShow",
        "summary": "Get a single team",
        "description": "Public info about a team. Includes the list of publicly visible leaders.",
        "tags": [
          "Teams"
        ],
        "security": []
      }
    },
    "/api/team/all": {
      "get": {
        "operationId": "teamAll",
        "summary": "Get popular teams",
        "description": "Paginator of the most popular teams.\n",
        "tags": [
          "Teams"
        ],
        "security": []
      }
    },
    "/api/team/of/{username}": {
      "get": {
        "operationId": "teamOfUsername",
        "summary": "Teams of a player",
        "description": "All the teams a player is a member of.\n",
        "tags": [
          "Teams"
        ],
        "security": []
      }
    },
    "/api/team/search": {
      "get": {
        "operationId": "teamSearch",
        "summary": "Search teams",
        "description": "Paginator of team search results for a keyword.\n",
        "tags": [
          "Teams"
        ],
        "security": []
      }
    },
    "/api/team/{teamId}/users": {
      "get": {
        "operationId": "teamIdUsers",
        "summary": "Get members of a team",
        "description": "Members are sorted by reverse chronological order of joining the team (most recent first).\nOAuth is only required if the list of members is private.\nUp to 5,000 users are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:read"
            ]
          }
        ]
      }
    },
    "/api/team/{teamId}/arena": {
      "get": {
        "operationId": "apiTeamArena",
        "summary": "Get team Arena tournaments",
        "description": "Get all Arena tournaments relevant to a team.\nTournaments are sorted by reverse chronological order of start date (last starting first).\nTournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n",
        "tags": [
          "Teams",
          "Arena tournaments"
        ],
        "security": []
      }
    },
    "/team/{teamId}/join": {
      "post": {
        "operationId": "teamIdJoin",
        "summary": "Join a team",
        "description": "Join a team.\nIf the team requires a password but the `password` field is incorrect,\nthen the call fails with `403 Forbidden`.\nSimilarly, if the team join policy requires a confirmation but the\n`message` parameter is not given, then the call fails with\n`403 Forbidden`.\n",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:write"
            ]
          }
        ]
      }
    },
    "/team/{teamId}/quit": {
      "post": {
        "operationId": "teamIdQuit",
        "summary": "Leave a team",
        "description": "Leave a team.\n- <https://lichess.org/team>\n",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:write"
            ]
          }
        ]
      }
    },
    "/api/team/{teamId}/requests": {
      "get": {
        "operationId": "teamRequests",
        "summary": "Get join requests",
        "description": "Get pending join requests of your team",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:read"
            ]
          }
        ]
      }
    },
    "/api/team/{teamId}/request/{userId}/accept": {
      "post": {
        "operationId": "teamRequestAccept",
        "summary": "Accept join request",
        "description": "Accept someone's request to join your team",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:lead"
            ]
          }
        ]
      }
    },
    "/api/team/{teamId}/request/{userId}/decline": {
      "post": {
        "operationId": "teamRequestDecline",
        "summary": "Decline join request",
        "description": "Decline someone's request to join your team",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:lead"
            ]
          }
        ]
      }
    },
    "/api/team/{teamId}/kick/{userId}": {
      "post": {
        "operationId": "teamIdKickUserId",
        "summary": "Kick a user from your team",
        "description": "Kick a member out of one of your teams.\n- <https://lichess.org/team>\n",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:lead"
            ]
          }
        ]
      }
    },
    "/team/{teamId}/pm-all": {
      "post": {
        "operationId": "teamIdPmAll",
        "summary": "Message all members",
        "description": "Send a private message to all members of a team.\nYou must be a team leader with the \"Messages\" permission.\n",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "OAuth2": [
              "team:lead"
            ]
          }
        ]
      }
    },
    "/api/streamer/live": {
      "get": {
        "operationId": "streamerLive",
        "summary": "Get live streamers",
        "description": "Get basic info about currently streaming users.\nThis API is very fast and cheap on lichess side.\nSo you can call it quite often (like once every 5 seconds).\n",
        "tags": [
          "Users"
        ],
        "security": []
      }
    },
    "/api/crosstable/{user1}/{user2}": {
      "get": {
        "operationId": "apiCrosstable",
        "summary": "Get crosstable",
        "description": "Get total number of games, and current score, of any two users.\nIf the `matchup` flag is provided, and the users are currently playing, also gets the current match game number and scores.\n",
        "tags": [
          "Users"
        ],
        "security": []
      }
    },
    "/api/player/autocomplete": {
      "get": {
        "operationId": "apiPlayerAutocomplete",
        "summary": "Autocomplete usernames",
        "description": "Provides autocompletion options for an incomplete username.\n",
        "tags": [
          "Users"
        ],
        "security": []
      }
    },
    "/api/user/{username}/note": {
      "post": {
        "operationId": "writeNote",
        "summary": "Add a note for a user",
        "description": "Add a private note available only to you about this account.\n",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      },
      "get": {
        "operationId": "readNote",
        "summary": "Get notes for a user",
        "description": "Get the private notes that you have added for a user.\n",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/rel/following": {
      "get": {
        "operationId": "apiUserFollowing",
        "summary": "Get users followed by the logged in user",
        "description": "Users are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "OAuth2": [
              "follow:read"
            ]
          }
        ]
      }
    },
    "/api/rel/follow/{username}": {
      "post": {
        "operationId": "followUser",
        "summary": "Follow a player",
        "description": "Follow a player, adding them to your list of Lichess friends.\n",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "OAuth2": [
              "follow:write"
            ]
          }
        ]
      }
    },
    "/api/rel/unfollow/{username}": {
      "post": {
        "operationId": "unfollowUser",
        "summary": "Unfollow a player",
        "description": "Unfollow a player, removing them from your list of Lichess friends.\n",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "OAuth2": [
              "follow:write"
            ]
          }
        ]
      }
    },
    "/api/rel/block/{username}": {
      "post": {
        "operationId": "blockUser",
        "summary": "Block a player",
        "description": "Block a player, adding them to your list of blocked Lichess users.\n",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "OAuth2": [
              "follow:write"
            ]
          }
        ]
      }
    },
    "/api/rel/unblock/{username}": {
      "post": {
        "operationId": "unblockUser",
        "summary": "Unblock a player",
        "description": "Unblock a player, removing them from your list of blocked Lichess users.\n",
        "tags": [
          "Relations"
        ],
        "security": [
          {
            "OAuth2": [
              "follow:write"
            ]
          }
        ]
      }
    },
    "/api/stream/event": {
      "get": {
        "operationId": "apiStreamEvent",
        "summary": "Stream incoming events",
        "description": "Stream the events reaching a lichess user in real time as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\nAn empty line is sent every 6 seconds for keep alive purposes.\n\nEach non-empty line is a JSON object containing a `type` field. Possible values are:\n- `gameStart` Start of a game\n- `gameFinish` Completion of a game\n- `challenge` A player sends you a challenge or you challenge someone\n- `challengeCanceled` A player cancels their challenge to you\n- `ch[...]",
        "tags": [
          "Board",
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:read",
              "bot:play",
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/seek": {
      "post": {
        "operationId": "apiBoardSeek",
        "summary": "Create a seek",
        "description": "Create a public seek, to start a game with a random player.\n\n### Real-time seek\n\nSpecify the `time` and `increment` clock values.\nThe response is streamed but doesn't contain any information.\n\n**Keep the connection open to keep the seek active**.\n\nIf the client closes the connection, the seek is canceled. This way, if the client terminates, the user won't be paired in a game they wouldn't play.\nWhen the seek is accepted, or expires, the server closes the connect[...]",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/stream/{gameId}": {
      "get": {
        "operationId": "boardGameStream",
        "summary": "Stream Board game state",
        "description": "Stream the state of a game being played with the Board API, as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\nUse this endpoint to get updates about the game in real-time, with a single request.\n\nEach line is a JSON object containing a `type` field. Possible values are:\n  - `gameFull` Full game data. All values are immutable, except for the `state` field.\n  - `gameState` Current state of the game. Immutable values not included. Sent when a move is played, [...]",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/move/{move}": {
      "post": {
        "operationId": "boardGameMove",
        "summary": "Make a Board move",
        "description": "Make a move in a game being played with the Board API.\nThe move can also contain a draw offer/agreement.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/chat": {
      "post": {
        "operationId": "boardGameChatPost",
        "summary": "Write in the chat",
        "description": "Post a message to the player or spectator chat, in a game being played with the Board API.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      },
      "get": {
        "operationId": "boardGameChatGet",
        "summary": "Fetch the game chat",
        "description": "Get the messages posted in the game chat\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/abort": {
      "post": {
        "operationId": "boardGameAbort",
        "summary": "Abort a game",
        "description": "Abort a game being played with the Board API.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/resign": {
      "post": {
        "operationId": "boardGameResign",
        "summary": "Resign a game",
        "description": "Resign a game being played with the Board API.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/draw/{accept}": {
      "post": {
        "operationId": "boardGameDraw",
        "summary": "Handle draw offers",
        "description": "Create/accept/decline draw offers.\n- `yes`: Offer a draw, or accept the opponent's draw offer.\n- `no`: Decline a draw offer from the opponent.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/takeback/{accept}": {
      "post": {
        "operationId": "boardGameTakeback",
        "summary": "Handle takeback offers",
        "description": "Create/accept/decline takebacks.\n- `yes`: Propose a takeback, or accept the opponent's takeback offer.\n- `no`: Decline a takeback offer from the opponent.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/claim-victory": {
      "post": {
        "operationId": "boardGameClaimVictory",
        "summary": "Claim victory of a game",
        "description": "Claim victory when the opponent has left the game for a while.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/board/game/{gameId}/berserk": {
      "post": {
        "operationId": "boardGameBerserk",
        "summary": "Berserk a tournament game",
        "description": "Go berserk on an arena tournament game. Halves the clock time, grants an extra point upon winning.\nOnly available in arena tournaments that allow berserk, and before each player has made a move.\n",
        "tags": [
          "Board"
        ],
        "security": [
          {
            "OAuth2": [
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/bot/online": {
      "get": {
        "operationId": "apiBotOnline",
        "summary": "Get online bots",
        "tags": [
          "Bot"
        ],
        "security": [],
        "description": "Stream the [online bot users](https://lichess.org/player/bots), as [ndjson](#section/Introduction/Streaming-with-ND-JSON). Throttled to 50 bot users per second."
      }
    },
    "/api/bot/account/upgrade": {
      "post": {
        "operationId": "botAccountUpgrade",
        "summary": "Upgrade to Bot account",
        "description": "Upgrade a lichess player account into a Bot account. Only Bot accounts can use the Bot API.\nThe account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.\nTo upgrade an account to Bot, use the [official lichess-bot client](https://github.com/lichess-bot-devs/lichess-bot), or follow these steps:\n- Create an [API access token](https://lichess.org/account/oauth/token/create?scopes[...]",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/stream/{gameId}": {
      "get": {
        "operationId": "botGameStream",
        "summary": "Stream Bot game state",
        "description": "Stream the state of a game being played with the Bot API, as [ndjson](#section/Introduction/Streaming-with-ND-JSON).\nUse this endpoint to get updates about the game in real-time, with a single request.\nEach line is a JSON object containing a `type` field. Possible values are:\n- `gameFull` Full game data. All values are immutable, except for the `state` field.\n- `gameState` Current state of the game. Immutable values not included.\n- `chatLine` Chat message sent by a u[...]",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/{gameId}/move/{move}": {
      "post": {
        "operationId": "botGameMove",
        "summary": "Make a Bot move",
        "description": "Make a move in a game being played with the Bot API.\nThe move can also contain a draw offer/agreement.\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/{gameId}/chat": {
      "post": {
        "operationId": "botGameChat",
        "summary": "Write in the chat",
        "description": "Post a message to the player or spectator chat, in a game being played with the Bot API.\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      },
      "get": {
        "operationId": "botGameChatGet",
        "summary": "Fetch the game chat",
        "description": "Get the messages posted in the game chat\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/{gameId}/abort": {
      "post": {
        "operationId": "botGameAbort",
        "summary": "Abort a game",
        "description": "Abort a game being played with the Bot API.\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/{gameId}/resign": {
      "post": {
        "operationId": "botGameResign",
        "summary": "Resign a game",
        "description": "Resign a game being played with the Bot API.\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/{gameId}/draw/{accept}": {
      "post": {
        "operationId": "botGameDraw",
        "summary": "Handle draw offers",
        "description": "Create/accept/decline draw offers with the Bot API.\n- `yes`: Offer a draw, or accept the opponent's draw offer.\n- `no`: Decline a draw offer from the opponent.\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/{gameId}/takeback/{accept}": {
      "post": {
        "operationId": "botGameTakeback",
        "summary": "Handle takeback offers",
        "description": "Create/accept/decline takebacks with the Bot API.\n- `yes`: Propose a takeback, or accept the opponent's takeback offer.\n- `no`: Decline a takeback offer from the opponent.\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/bot/game/{gameId}/claim-victory": {
      "post": {
        "operationId": "botGameClaimVictory",
        "summary": "Claim victory of a game",
        "description": "Claim victory when the opponent has left the game for a while.\n",
        "tags": [
          "Bot"
        ],
        "security": [
          {
            "OAuth2": [
              "bot:play"
            ]
          }
        ]
      }
    },
    "/api/challenge": {
      "get": {
        "operationId": "challengeList",
        "summary": "List your challenges",
        "description": "Get a list of challenges created by or targeted at you.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:read"
            ]
          }
        ]
      }
    },
    "/api/challenge/{username}": {
      "post": {
        "operationId": "challengeCreate",
        "summary": "Create a challenge",
        "description": "Challenge someone to play. The targeted player can choose to accept or decline.\nIf the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)\nthat a new game has started. The game ID will be the same as the challenge ID.\nChallenges for realtime games (not correspondence) expire after 20s if not accepted.\nTo prevent that, use the `keepAliveStream` flag described below.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:write",
              "bot:play",
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/challenge/{challengeId}/show": {
      "get": {
        "operationId": "challengeShow",
        "summary": "Show one challenge",
        "description": "Get details about a challenge, even if it has been recently accepted, canceled or declined.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:read"
            ]
          }
        ]
      }
    },
    "/api/challenge/{challengeId}/accept": {
      "post": {
        "operationId": "challengeAccept",
        "summary": "Accept a challenge",
        "description": "Accept an incoming challenge.\nYou should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:write",
              "bot:play",
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/challenge/{challengeId}/decline": {
      "post": {
        "operationId": "challengeDecline",
        "summary": "Decline a challenge",
        "description": "Decline an incoming challenge.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:write",
              "bot:play",
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/challenge/{challengeId}/cancel": {
      "post": {
        "operationId": "challengeCancel",
        "summary": "Cancel a challenge",
        "description": "Cancel a challenge you sent, or aborts the game if the challenge was accepted, but the game was not yet played.\nNote that the ID of a game is the same as the ID of the challenge that created it.\nWorks for user challenges and open challenges alike.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:write",
              "bot:play",
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/challenge/ai": {
      "post": {
        "operationId": "challengeAi",
        "summary": "Challenge the AI",
        "description": "Start a game with Lichess AI.\nYou will be notified on the [event stream](#operation/apiStreamEvent) that a new game has started.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:write",
              "bot:play",
              "board:play"
            ]
          }
        ]
      }
    },
    "/api/challenge/open": {
      "post": {
        "operationId": "challengeOpen",
        "summary": "Open-ended challenge",
        "description": "Create a challenge that any 2 players can join.\nShare the URL of the challenge. the first 2 players to click it will be paired for a game.\nThe response body also contains `whiteUrl` and `blackUrl`.\nYou can control which color each player gets by giving them these URLs,\ninstead of the main challenge URL.\nOpen challenges expire after 24h.\nIf the challenge creation is [authenticated with OAuth2](#section/Introduction/Authentication),\nthen you can use the [challenge ca[...]",
        "tags": [
          "Challenges"
        ],
        "security": []
      }
    },
    "/api/challenge/{gameId}/start-clocks": {
      "post": {
        "operationId": "challengeStartClocks",
        "summary": "Start clocks of a game",
        "description": "Start the clocks of a game immediately, even if a player has not yet made a move.\nRequires the OAuth tokens of both players with `challenge:write` scope.\nIf the clocks have already started, the call will have no effect.\n\nFor AI games with only one player, omit the `token2` parameter.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:write"
            ]
          }
        ]
      }
    },
    "/api/bulk-pairing": {
      "get": {
        "operationId": "bulkPairingList",
        "summary": "View your bulk pairings",
        "description": "Get a list of bulk pairings you created.\n",
        "tags": [
          "Bulk pairings"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:bulk"
            ]
          }
        ]
      },
      "post": {
        "operationId": "bulkPairingCreate",
        "summary": "Create a bulk pairing",
        "description": "Schedule many games at once, up to 24h in advance.\nOAuth tokens are required for all paired players, with the `challenge:write` scope.\nYou can schedule up to 500 games every 10 minutes. [Contact us](mailto:contact@lichess.org) if you need higher limits.\nIf games have a real-time clock, each player must have only one pairing.\nFor correspondence games, players can have multiple pairings within the same bulk.\n\n**The entire bulk is rejected if:**\n  - a token is missing[...]",
        "tags": [
          "Bulk pairings"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:bulk"
            ]
          }
        ]
      }
    },
    "/api/bulk-pairing/{id}/start-clocks": {
      "post": {
        "operationId": "bulkPairingStartClocks",
        "summary": "Manually start clocks",
        "description": "Immediately start all clocks of the games of a bulk pairing.\nThis overrides the `startClocksAt` value of an existing bulk pairing.\nIf the games have not yet been created (`bulk.pairAt` is in the future), then this does nothing.\nIf the clocks have already started (`bulk.startClocksAt` is in the past), then this does nothing.\n",
        "tags": [
          "Bulk pairings"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:bulk"
            ]
          }
        ]
      }
    },
    "/api/bulk-pairing/{id}": {
      "get": {
        "operationId": "bulkPairingGet",
        "summary": "Show a bulk pairing",
        "description": "Get a single bulk pairing by its ID.\n",
        "tags": [
          "Bulk pairings"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:bulk"
            ]
          }
        ]
      },
      "delete": {
        "operationId": "bulkPairingDelete",
        "summary": "Cancel a bulk pairing",
        "description": "Cancel and delete a bulk pairing that is scheduled in the future.\nIf the games have already been created, then this does nothing.\nCanceling a bulk pairing does not refund the rate limit cost of that bulk pairing.\n",
        "tags": [
          "Bulk pairings"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:bulk"
            ]
          }
        ]
      }
    },
    "/api/bulk-pairing/{id}/games": {
      "get": {
        "operationId": "bulkPairingIdGamesGet",
        "summary": "Export games of a bulk pairing",
        "description": "Download games of a bulk in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request `Accept` header.\n",
        "tags": [
          "Bulk pairings"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:bulk"
            ]
          }
        ]
      }
    },
    "/api/round/{gameId}/add-time/{seconds}": {
      "post": {
        "operationId": "roundAddTime",
        "summary": "Add time to the opponent clock",
        "description": "Add seconds to the opponent's clock. Can be used to create games with time odds.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "challenge:write"
            ]
          }
        ]
      }
    },
    "/api/token/admin-challenge": {
      "post": {
        "operationId": "adminChallengeTokens",
        "summary": "Admin challenge tokens",
        "description": "**This endpoint can only be used by Lichess administrators. It will not work if you do not have the appropriate permissions.** Tournament organizers should instead use [OAuth](#tag/OAuth) to obtain `challenge:write` tokens from users in order to perform bulk pairing.*\nCreate and obtain `challenge:write` tokens for multiple users.\nIf a similar token already exists for a user, it is reused. This endpoint is idempotent.\n",
        "tags": [
          "Challenges"
        ],
        "security": [
          {
            "OAuth2": [
              "web:mod"
            ]
          }
        ]
      }
    },
    "/inbox/{username}": {
      "post": {
        "operationId": "inboxUsername",
        "summary": "Send a private message",
        "description": "Send a private message to another player.\n",
        "tags": [
          "Messaging"
        ],
        "security": [
          {
            "OAuth2": [
              "msg:write"
            ]
          }
        ]
      }
    },
    "/api/cloud-eval": {
      "get": {
        "operationId": "apiCloudEval",
        "summary": "Get cloud evaluation of a position.",
        "description": "Get the cached evaluation of a position, if available.\nOpening positions have more chances of being available. There are about 15 million positions in the database.\nUp to 5 variations may be available. Variants are supported.\nUse this endpoint to fetch a few positions here and there.\nIf you want to download a lot of positions, [get the full list](https://database.lichess.org/#evals) from our exported database.\n",
        "tags": [
          "Analysis"
        ],
        "security": []
      }
    },
    "/api/external-engine": {
      "get": {
        "operationId": "apiExternalEngineList",
        "summary": "List external engines",
        "tags": [
          "External engine"
        ],
        "security": [
          {
            "OAuth2": [
              "engine:read"
            ]
          }
        ],
        "description": "Lists all external engines that have been registered for the user,\nand the credentials required to use them.\n"
      },
      "post": {
        "operationId": "apiExternalEngineCreate",
        "summary": "Create external engine",
        "tags": [
          "External engine"
        ],
        "security": [
          {
            "OAuth2": [
              "engine:write"
            ]
          }
        ],
        "description": "Registers a new external engine for the user. It can then be selected\nand used on the analysis board.\nAfter registering, the provider should start waiting for analyis requests.\n"
      }
    },
    "/api/external-engine/{id}": {
      "get": {
        "operationId": "apiExternalEngineGet",
        "summary": "Get external engine",
        "tags": [
          "External engine"
        ],
        "security": [
          {
            "OAuth2": [
              "engine:read"
            ]
          }
        ],
        "description": "Get properties and credentials of an external engine.\n"
      },
      "put": {
        "operationId": "apiExternalEnginePut",
        "summary": "Update external engine",
        "tags": [
          "External engine"
        ],
        "security": [
          {
            "OAuth2": [
              "engine:write"
            ]
          }
        ],
        "description": "Updates the properties of an external engine.\n"
      },
      "delete": {
        "operationId": "apiExternalEngineDelete",
        "summary": "Delete external engine",
        "tags": [
          "External engine"
        ],
        "security": [
          {
            "OAuth2": [
              "engine:write"
            ]
          }
        ],
        "description": "Unregisters an external engine.\n"
      }
    },
    "/api/external-engine/{id}/analyse": {
      "servers": [
        {
          "url": "https://engine.lichess.ovh"
        }
      ],
      "post": {
        "operationId": "apiExternalEngineAnalyse",
        "summary": "Analyse with external engine",
        "tags": [
          "External engine"
        ],
        "security": [],
        "description": "**Endpoint: `https://engine.lichess.ovh/api/external-engine/{id}/analyse`**\nRequest analysis from an external engine.\nResponse content is streamed as [newline delimited JSON](#section/Introduction/Streaming-with-ND-JSON).\nThe properties are based on the [UCI specification](https://backscattering.de/chess/uci/#engine).\nAnalysis stops when the client goes away, the requested limit\nis reached, or the provider goes away.\n"
      }
    },
    "/api/external-engine/work": {
      "servers": [
        {
          "url": "https://engine.lichess.ovh"
        }
      ],
      "post": {
        "operationId": "apiExternalEngineAcquire",
        "summary": "Acquire analysis request",
        "tags": [
          "External engine"
        ],
        "security": [],
        "description": "**Endpoint: `https://engine.lichess.ovh/api/external-engine/work`**\nWait for an analysis requests to any of the external engines that\nhave been registered with the given `secret`.\nUses long polling.\nAfter acquiring a request, the provider should immediately\n[start streaming the results](#tag/External-engine/operation/apiExternalEngineSubmit).\n"
      }
    },
    "/api/external-engine/work/{id}": {
      "servers": [
        {
          "url": "https://engine.lichess.ovh"
        }
      ],
      "post": {
        "operationId": "apiExternalEngineSubmit",
        "summary": "Answer analysis request",
        "tags": [
          "External engine"
        ],
        "security": [],
        "description": "**Endpoint: `https://engine.lichess.ovh/api/external-engine/work/{id}`**\nSubmit a stream of analysis as [UCI output](https://backscattering.de/chess/uci/#engine-info).\n* The engine should always be in `UCI_Chess960` mode.\n* `UCI_AnalyseMode` enabled if available.\n* It produces `info` with at least:\n  - `depth`\n  - `multipv` (between 1 and 5)\n  - `score`\n  - `nodes`\n  - `time`\n  - `pv`\nThe server may close the connection at any time, indicating that\nthe request[...]"
      }
    },
    "/oauth": {
      "get": {
        "operationId": "oauth",
        "summary": "Request authorization code",
        "tags": [
          "OAuth"
        ],
        "security": [],
        "description": "OAuth2 authorization endpoint.\nStart the OAuth2 Authorization Code Flow with PKCE by securely\ngenerating two random strings unique to each authorization\nrequest:\n\n* `code_verifier`\n* `state`\n\nStore these in session storage. Make sure not to reveal `code_verifier`\nto eavesdroppers. Do not show it in URLs, do not abuse `state` to store\nit, do not send it over insecure connections. However it is fine if\nthe user themselves can extract `code_verifier`, which will a[...]"
      }
    },
    "/api/token": {
      "post": {
        "operationId": "apiToken",
        "summary": "Obtain access token",
        "tags": [
          "OAuth"
        ],
        "security": [],
        "description": "OAuth2 token endpoint. Exchanges an authorization code for an access token.\n"
      },
      "delete": {
        "operationId": "apiTokenDelete",
        "summary": "Revoke access token",
        "description": "Revokes the access token sent as Bearer for this request.",
        "tags": [
          "OAuth"
        ],
        "security": [
          {
            "OAuth2": []
          }
        ]
      }
    },
    "/api/token/test": {
      "post": {
        "operationId": "tokenTest",
        "summary": "Test multiple OAuth tokens",
        "description": "For up to 1000 OAuth tokens,\nreturns their associated user ID and scopes,\nor `null` if the token is invalid.\nThe method is `POST` so a longer list of tokens can be sent in the request body.\n",
        "tags": [
          "OAuth"
        ],
        "security": []
      }
    },
    "/masters": {
      "servers": [
        {
          "url": "https://explorer.lichess.ovh"
        }
      ],
      "get": {
        "operationId": "openingExplorerMaster",
        "summary": "Masters database",
        "description": "**Endpoint: <https://explorer.lichess.ovh/masters>**\n\nExample: `curl https://explorer.lichess.ovh/masters?play=d2d4,d7d5,c2c4,c7c6,c4d5`\n",
        "tags": [
          "Opening Explorer"
        ],
        "security": []
      }
    },
    "/lichess": {
      "servers": [
        {
          "url": "https://explorer.lichess.ovh"
        }
      ],
      "get": {
        "operationId": "openingExplorerLichess",
        "summary": "Lichess games",
        "description": "**Endpoint: <https://explorer.lichess.ovh/lichess>**\n\nGames sampled from all Lichess players.\n\nExample: `curl https://explorer.lichess.ovh/lichess?variant=standard&speeds=blitz,rapid,classical&ratings=2200,2500&fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201`\n",
        "tags": [
          "Opening Explorer"
        ],
        "security": []
      }
    },
    "/player": {
      "servers": [
        {
          "url": "https://explorer.lichess.ovh"
        }
      ],
      "get": {
        "operationId": "openingExplorerPlayer",
        "summary": "Player games",
        "description": "**Endpoint: <https://explorer.lichess.ovh/player>**\n\nGames of a Lichess player.\n\nResponds with a stream of [newline delimited JSON](#section/Introduction/Streaming-with-ND-JSON). Will start indexing\non demand, immediately respond with the current results, and stream\nmore updates until indexing is complete. The stream is throttled\nand deduplicated. Empty lines may be sent to avoid timeouts.\n\nWill index new games at most once per minute, and revisit previously\nong[...]",
        "tags": [
          "Opening Explorer"
        ],
        "security": []
      }
    },
    "/master/pgn/{gameId}": {
      "servers": [
        {
          "url": "https://explorer.lichess.ovh"
        }
      ],
      "get": {
        "operationId": "openingExplorerMasterGame",
        "summary": "OTB master game",
        "description": "**Endpoint: `https://explorer.lichess.ovh/masters/pgn/{gameId}`**\n\nExample: `curl https://explorer.lichess.ovh/masters/pgn/aAbqI4ey`\n",
        "tags": [
          "Opening Explorer"
        ],
        "security": []
      }
    },
    "/standard": {
      "servers": [
        {
          "url": "https://tablebase.lichess.ovh"
        }
      ],
      "get": {
        "operationId": "tablebaseStandard",
        "summary": "Tablebase lookup",
        "description": "**Endpoint: <https://tablebase.lichess.ovh>**\nExample: `curl http://tablebase.lichess.ovh/standard?fen=4k3/6KP/8/8/8/8/7p/8_w_-_-_0_1`\n",
        "tags": [
          "Tablebase"
        ],
        "security": []
      }
    },
    "/atomic": {
      "servers": [
        {
          "url": "https://tablebase.lichess.ovh"
        }
      ],
      "get": {
        "operationId": "tablebaseAtomic",
        "summary": "Tablebase lookup for Atomic chess",
        "description": "**Endpoint: <https://tablebase.lichess.ovh>**\n",
        "tags": [
          "Tablebase"
        ],
        "security": []
      }
    },
    "/antichess": {
      "servers": [
        {
          "url": "https://tablebase.lichess.ovh"
        }
      ],
      "get": {
        "operationId": "antichessAtomic",
        "summary": "Tablebase lookup for Antichess",
        "description": "**Endpoint: <https://tablebase.lichess.ovh>**\n",
        "tags": [
          "Tablebase"
        ],
        "security": []
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "Read [the introduction for how to make authenticated requests](#section/Introduction/Authentication).\n",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://lichess.org/oauth",
            "tokenUrl": "https://lichess.org/api/token",
            "scopes": {
              "preference:read": "Read your preferences",
              "preference:write": "Write your preferences",
              "email:read": "Read your email address",
              "engine:read": "Read your external engines",
              "engine:write": "Create, update, delete your external engines",
              "challenge:read": "Read incoming challenges",
              "challenge:write": "Create, accept, decline challenges",
              "challenge:bulk": "Create, delete, query bulk pairings",
              "study:read": "Read private studies and broadcasts",
              "study:write": "Create, update, delete studies and broadcasts",
              "tournament:write": "Create tournaments",
              "racer:write": "Create and join puzzle races",
              "puzzle:read": "Read puzzle activity",
              "team:read": "Read private team information",
              "team:write": "Join, leave teams",
              "team:lead": "Manage teams (kick members, send PMs)",
              "follow:read": "Read followed players",
              "follow:write": "Follow and unfollow other players",
              "msg:write": "Send private messages to other players",
              "board:play": "Play with the Board API",
              "bot:play": "Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)",
              "web:mod": "Use moderator tools (within the bounds of your permissions)"
            }
          }
        }
      }
    }
  }
}